version: 2
jobs:
  test:
    docker:
      - image: circleci/node:8.9.4

    working_directory: /tmp/ephemeralkey

    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: Install system dependencies
          command: sudo apt-get update && sudo apt install -y libusb-1.0-0 libusb-1.0-0-dev
      - run:
          name: Install node dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: Run tests
          command: npm run test

  build:
    docker:
      - image: circleci/node:8.9.4

    working_directory: /tmp/ephemeralkey

    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: Install system dependencies
          command: sudo apt-get update && sudo apt install -y libusb-1.0-0 libusb-1.0-0-dev
      - run:
          name: Install node dependencies
          command: npm install
      - run:
          name: Build library
          command: npm run build
      - save_cache:
          paths:
            - dist
          key: dist-{{ .Branch }}-{{ .Revision }}

workflows:
  version: 2
  build:
    jobs:
      - test
      - build:
          requires:
            - test
