version: 2
jobs:
  test:
    docker:
      - image: circleci/node:8-browsers
        environment:
          CHROME_BIN: '/usr/bin/google-chrome'
      - image: ethereum/client-go
        command: |
          --identity="TEST_NODE"
          --networkid="53611"
          --rpc
          --rpcaddr 0.0.0.0
          --rpcapi admin,debug,eth,miner,net,personal,shh,txpool,web3
          --ws
          --wsaddr 0.0.0.0
          --wsapi admin,debug,eth,miner,net,personal,shh,txpool,web3
          --wsorigins "*"
          --mine
          --minerthreads=1
          --dev

    working_directory: /tmp/ephemeralkey

    steps:
      - checkout
      - setup_remote_docker:
          version: 17.05.0-ce
      - restore_cache:
          keys:
            - dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: Download Selenium
          command: curl -O http://selenium-release.storage.googleapis.com/3.5/selenium-server-standalone-3.5.3.jar
      - run:
          name: Install node dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: build for end2end
          command: npm run build
      - run:
          name: Run tests
          command: ./scripts/test-circle.sh

  build:
    docker:
      - image: circleci/node:8

    working_directory: /tmp/ephemeralkey

    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: Install node dependencies
          command: npm install
      - run:
          name: Build library
          command: npm run build
      - save_cache:
          paths:
            - dist
          key: dist-{{ .Branch }}-{{ .Revision }}

workflows:
  version: 2
  build:
    jobs:
      - test
      - build:
          requires:
            - test
